spring:
  datasource:
    url: "${dev.spring.mysql.url}"
    username: "${dev.spring.mysql.username}"
    password: "${dev.spring.mysql.password}"
    driver-class-name: "${dev.spring.mysql.driver-class-name}"
  data:
    mongodb:
      uri: "${dev.spring.mongoDB.uri}"
    redis:
      host: "${dev.spring.redis.host}"
      port: "${dev.spring.redis.port}"
    elasticsearch:
      repositories:
        enabled: true

  docker:
    compose:
      enabled: false
  elasticsearch:
      uris: http://localhost:9200


  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data:
          elasticsearch: DEBUG
          jpa: DEBUG
custom:
  elasticsearch:
    uri: "${dev.spring.elasticsearch.uris}"


jwt:
  secret: "${dev.security.jwt.secret}"

livekit:
  websocketURL: "${dev.livekit.sebsocketURL}"
  apiKey: "${dev.livekit.apiKey}"
  apiSecret: "${dev.livekit.apiSecret}"

