spring:
  datasource:
    url: "${dev.spring.mysql.url}"
    username: "${dev.spring.mysql.username}"
    password: "${dev.spring.mysql.password}"
    driver-class-name: "${dev.spring.mysql.driver-class-name}"
  data:
    mongodb:
      uri: "${dev.spring.mongoDB.uri}"
    redis:
      host: "${dev.spring.redis.host}"
      port: "${dev.spring.redis.port}"
  docker:
    compose:
      enabled: false
  elasticsearch:
    restclient:
      uris: "${dev.spring.elasticsearch.uris}"
      # 필요한 경우 타임아웃이나 인증 정보도 추가할 수 있습니다.
      # connection-timeout: 5000
      # read-timeout: 60000
    rest:
      uris: "${dev.spring.elasticsearch.uris}"
      # 필요한 경우 타임아웃이나 인증 정보도 추가할 수 있습니다.
      # connection-timeout: 5000
      # read-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data:
          elasticsearch: DEBUG
          jpa: DEBUG
custom:
  elasticsearch:
    uri: "${dev.spring.elasticsearch.uris}"


jwt:
  secret: "${dev.security.jwt.secret}"

livekit:
  websocketURL: "${dev.livekit.sebsocketURL}"
  apiKey: "${dev.livekit.apiKey}"
  apiSecret: "${dev.livekit.apiSecret}"